{% set name = "django-auth-ldap" %}
{% set version = "1.2.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 25dc2b4302039c1d246f166c98cd23f3260bdb13b01fdd36c9fe184c0d777b0f

build:
  number: 0
  script: "python setup.py install"

requirements:
  host:
    - django
    - pip
    - python-ldap
    - python
  run:
    - django
    - python-ldap
    - python

about:
  home: https://github.com/django-auth-ldap/django-auth-ldap
  license: BSD
  license_family: BSD
  license_file: 
  summary: Django LDAP authentication backend
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
