{% set name = "django-celery-beat" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/celery/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d03b414affcb8c8c19d9f88e9ada977a900b84994daaf094609aca207cc2fed0

build:
  number: 0
  script: "python setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - celery >=4.0,<5.0
    - pip
    - python
    - setuptools
  run:
    - celery >=4.0,<5.0
    - python
    - setuptools

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  requires:
    - case >=1.3.1
    - django
    - pytest >=3.0
    - pytest-django
    - pytz >dev

about:
  home: https://github.com/celery/django-celery-beat
  license: BSD
  license_family: BSD
  license_file: 
  summary: Database-backed Periodic Tasks.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
