notifications:
  email: false

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  postgresql: "9.3"

before_install:
    - sudo apt-get -y install libpq-dev python-dev python-software-properties python-pip git
    - sudo apt-get -y install libcurl4-gnutls-dev
    - sudo apt-get -y install software-properties-common
    - sudo rm /etc/apt/sources.list.d/ubuntugis-stable-source.list
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get -yqq update
    - sudo apt-get -y install gdal-bin libgdal-dev libgeos-dev libspatialite-dev libspatialite5 libgeos-c1v5 spatialite-bin zip unzip libxml2-dev libxslt-dev
    - sudo apt-get -y install postgis postgresql-contrib-9.3
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal

before_script:
    - psql -U postgres -c "create extension postgis"
    - createuser hot --superuser --createdb -U postgres

install:
    "pip install -r requirements-dev.txt"

# command to run tests
script:
    ./manage.py test


