notifications:
  email: false

sudo: required
dist: trusty
language: generic

services:
  - docker

#before_install:
#    - sudo mv /etc/apt/sources.list.d/* /tmp
#    - sudo apt-get -qq remove postgis
#    - sudo apt-get -y install software-properties-common
#    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
#    - sudo apt-get clean
#    - sudo apt-get update
#    - sudo apt-get -y remove python python-pip python-gdal git postgresql-9.3-postgis-2.2 libpq-dev python-dev gcc g++ gdal-bin libgdal-dev libspatialite5 osmctools spatialite-bin zip unzip rabbitmq-server libxml2-dev libxslt-dev
#    - sudo apt-get -y install python python-pip python-gdal git postgresql-9.3-postgis-2.2 libpq-dev python-dev gcc g++ gdal-bin libgdal-dev libspatialite5 osmctools spatialite-bin zip unzip rabbitmq-server libxml2-dev libxslt-dev
#    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
#    - export C_INCLUDE_PATH=/usr/include/gdal
#    - sudo mkdir -p /home/ubuntu/export_staging
#    - sudo chmod 777 /home/ubuntu/export_staging
#
#install: pip install --user -r requirements-dev.txt

before_script:
    - docker-compose build

script:
    - docker-compose run eventkit /var/lib/eventkit/.virtualenvs/eventkit/bin/python /var/lib/eventkit/manage.py test eventkit_cloud
    - docker-compose run webpack npm test

env:
  - DATABASE_URL=postgis://eventkit:eventkit_exports@postgis:5432/eventkit_exports BROKER_URL=amqp://guest:guest@rabbitmq:5672/ DEBUG=True C_FORCE_ROOT=True PRODUCTION=True SITE_NAME=cloud.eventkit.dev EXPORT_STAGING_ROOT=/home/ubuntu/export_staging/ EXPORT_DOWNLOAD_ROOT=/home/ubuntu/exports_download/ AWS_BUCKET_NAME='eventkit'
