notifications:
  email: false

sudo: required
dist: trusty
language: generic

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
    - export SITE_IP=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
    - echo $SITE_IP
    - docker-compose -f docker-compose-test.yml build
    - docker-compose -f docker-compose-test.yml up -d
    - ping -c 4 $SITE_IP
    - ping -c 4 $SITE_NAME

script:
    #- docker-compose -f docker-compose-test.yml run -T -e COVERAGE=True -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} -e TRAVIS=True -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} -e TRAVIS_BRANCH=${TRAVIS_BRANCH} eventkit /var/lib/eventkit/.virtualenvs/eventkit/bin/python /var/lib/eventkit/manage.py test eventkit_cloud
    - docker-compose -f docker-compose-test.yml run -T evenktit /var/lib/eventkit/.virtualenvs/eventkit/bin/python manage.py migrate
    - docker-compose -f docker-compose-test.yml run -T eventkit /var/lib/eventkit/.virtualenvs/eventkit/bin/python manage.py loaddata eventkit_cloud/fixtures/providers.json
    - docker-compose -f docker-compose-test.yml run -T eventkit /var/lib/eventkit/.virtualenvs/eventkit/bin/python manage.py run_integration_tests

env:
  - DOCKER_COMPOSE_VERSION=1.9.0 SITE_NAME=cloud.eventkit.dev

