notifications:
  email: false

language: python

sudo: required
dist: trusty

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  postgresql: "9.3"

before_install:
    - sudo apt-get -y install software-properties-common python-pip git libpq-dev python-dev postgresql-9.3-postgis-2.1  gcc g++ gdal-bin libgdal-dev libgeos-dev libspatialite-dev libspatialite5 osmctools spatialite-bin libspatialite-dev zip unzip rabbitmq-server
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal

before_script:
    - psql -U postgres -c "create extension postgis"
    - createuser hot --superuser --createdb -U postgres

install:
    "pip install -r requirements-dev.txt"

# command to run tests
script:
    ./manage.py test


