notifications:
  email: false

language: generic

sudo: required
dist: trusty

python:
  - "2.7"

virtualenv:
  system_site_packages: true

addons:
  postgresql: "9.3"

before_install:
    - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
    - sudo apt-get -qq remove postgis
    - sudo apt-get -y install software-properties-common
    - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get clean
    - sudo apt-get update
    - sudo apt-get -y remove python-pip python-gdal git postgresql-9.3-postgis-2.2 libpq-dev python-dev gcc g++ gdal-bin libgdal-dev libspatialite5 osmctools spatialite-bin zip unzip rabbitmq-server libxml2-dev libxslt-dev
    - sudo apt-get -y install python-pip python-gdal git postgresql-9.3-postgis-2.2 libpq-dev python-dev gcc g++ gdal-bin libgdal-dev libspatialite5 osmctools spatialite-bin zip unzip rabbitmq-server libxml2-dev libxslt-dev
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal

before_script:
    - psql -U postgres -c "create extension postgis"
    - createuser hot --superuser --createdb -U postgres

install:
    "pip install -r requirements-dev.txt"

# command to run tests
script:
    ./manage.py test


