version: '2'
services:
  eventkit:
      build:
        context: .
      environment:
        - DATABASE_URL=postgis://postgres:postgres@postgres:5432/postgres
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
        - DEBUG=True
      depends_on:
        - postgres
        - rabbitmq
      links:
        - postgres
        - rabbitmq
      extra_hosts:
        - "cloud.eventkit.dev:127.0.0.1"
      ports:
        - "80:80"
  postgres:
    image: mdillon/postgis 
    environment:
      - DB_NAME=eventkit
      - DB_DATA_NAME=eventkit_data
      - DB_PASS=eventkit
      - DB_USER=eventkit
      - POSTGRES_USER=postgres
    ports:
     - "5432:5432"
  rabbitmq:
     image: rabbitmq
