version: '2'
services:
  eventkit:
      build:
        context: .
      environment:
        - DATABASE_URL=postgis://eventkit:eventkit_exports@postgis:5432/eventkit_exports
        - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
        - DEBUG=True
      depends_on:
        - postgis
        - rabbitmq
      links:
        - postgis
        - rabbitmq
      extra_hosts:
        - "cloud.eventkit.dev:127.0.0.1"
      ports:
        - "80:80"
      command: sh /var/lib/eventkit/scripts/eventkit-entrypoint.sh
  celery:
      extends:
        service: eventkit
      command: sh /var/lib/eventkit/scripts/celery-entrypoint.sh
  postgis:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=eventkit
      - POSTGRES_PASSWORD=eventkit_exports
      - POSTGRES_DB=eventkit_exports
    ports:
     - "5432:5432"
  rabbitmq:
     image: rabbitmq
