version: '2'
services:
  eventkit:
      build:
          context: .
          dockerfile: Dockerfile_eventkit
      depends_on:
        - postgis
        - rabbitmq
      links:
        - postgis
        - rabbitmq
      extra_hosts:
        - "cloud.eventkit.dev:127.0.0.1"
  postgis:
    build:
        context: .
        dockerfile: Dockerfile_postgis
    ports:
     - "5432:5432"
  rabbitmq:
    build:
        context: .
        dockerfile: Dockerfile_rabbitmq
  