name: eventkit-cloud
channels:
  - local
  - https://eventkit_readonly:eventkit-readonly@nexus.devops.geointservices.io/content/repositories/eventkit-Releases/
dependencies:
  - python=3.6
  - eventkit-cloud
