name: eventkit-cloud
channels:
  - local
dependencies:
  - python=3.6
  - eventkit-cloud
   # The eventkit-cloud recipe is in conda/recipes/eventkit-cloud/meta.yaml.
  - pip:
    - -r requirements-dev.txt
