{% set name = "django-celery-results" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/celery/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ad01484834387a3472a1ff5c20264ab31657b5b3d27c489efdb4321427005d80

build:
  number: 0
  script: "python setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - celery >=4.0,<5.0
    - kombu
    - pip
    - python
    - setuptools
  run:
    - celery >=4.0,<5.0
    - kombu
    - python
    - setuptools

about:
  home: https://github.com/celery/django-celery-results
  license: BSD
  license_family: BSD
  license_file: 
  summary: Celery result backends for Django.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
