{% set name = "eventkit-cloud" %}

package:
  name: '{{ name|lower }}'
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: /eventkit-cloud

build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  build:
    - python=3.7
    - pip
    - setuptools
    - wheel
    - nodejs
    - ruby
    - git
  run:
    - python=3.7
    - django-audit-logging=0.2.0
    - gdal=2.4.1
    - libgdal=2.4.1
    - osmctools=0.7.0
    - openldap=2.4.45
    - python-ldap=3.1.0
    - amqp=2.3.2
    - billiard=3.5.0.4
    - boto3=1.7.48
    - celery=4.2.1
    - certifi=2018.8.24
    - django=2.2.1
    - dj-database-url=0.4.2
    - django-auth-ldap=1.7.0
    - django-celery-beat=1.1.1
    - django-celery-results=1.0.1
    - django-extensions=1.9.9
    - django-filter=2.0.0
    - django-notifications-hq=1.5.0
    - djangorestframework=3.8.0
    - djangorestframework-gis=0.13
    - eventlet=0.23.0
    - gunicorn=19.9.0
    - kombu=4.2.1
    - lxml=4.3.3
    - MapProxy=1.11.0
    - Markdown=2.6.11
    - numpy=1.16.3
    - Pillow= 5.2.0
    - PyJWT=1.7.1
    - pyparsing=2.4.0
    - python-dateutil=2.7.2
    - python-magic=0.4.12
    - pytz=2018.5
    - PyYAML=3.12
    - requests=2.20.1
    - Shapely=1.6.4
    - simplejson=3.16.0
    - whitenoise=3.3.1

about:
  home: https://github.com/venicegeo/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/venicegeo/eventkit-cloud/blob/master/README.md'
  dev_url: 'https://github.com/venicegeo/eventkit-cloud'

extra:
  recipe-maintainers:
    - jsvrcek
